when:
  - event: push
    branch: main
  - event: manual

steps:
  build-api:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: registry.kcolb.com/suchventure/warden-api
      registry: registry.kcolb.com
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
      tags: latest
      dockerfile: Dockerfile
      context: .

  build-admin:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: registry.kcolb.com/suchventure/warden-admin
      registry: registry.kcolb.com
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
      tags: latest
      dockerfile: admin/Dockerfile
      context: admin/

  notify-dockhand-dolores:
    image: curlimages/curl:latest
    commands:
      - curl -X POST https://dockhand.kcolb.com/api/git/stacks/49/webhook
    when:
      event: push
      branch: main
    depends_on:
      - build-admin
      - build-api

  deploy:
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: dolores_host
      username: juha
      password:
        from_secret: dolores_password
      port: 22
      script:
        - docker pull registry.kcolb.com/suchventure/warden-api:latest
        - docker pull registry.kcolb.com/suchventure/warden-admin:latest
        - cd /srv/data/infra/stacks/dolores/warden && docker compose up -d --force-recreate --remove-orphans
    when:
      event: push
      branch: main
    depends_on:
      - build-admin
      - build-api
